[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.setup]
cmds = ["npm install -g pnpm@9"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"
