[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]
cacheDirectories = [".next/cache", "node_modules/.cache"]

[start]
cmd = "npm run start"
